- name: check selinux enforce

  hosts: all
  gather_facts: no

  tasks:
    - name: get sestatus
      command: getenforce
      register: sestatus
      become: yes
      become_method: sudo

    - name: fail if selinux is not set to enforcing
      fail:
        msg: "selinux not enabled"
      when:
        - 'Enforcing' not in sestatus.stdout
