- name: install docker and add a registry name to the list of insecure registry list

  hosts: all
  vars:
      insecure_registries: "empty"  #insecure
  gather_facts: no
  become: yes

  tasks:

    - name: install docker
      package:
        name: docker
        state: present

    - name: fail if registry name is not set
      fail:
        msg: "Please mention registry name - insecure_registries"
      when:
        - insecure_registries == "empty"

    - name: set_fact original_content
      set_fact:
        original_content: "{{ lookup('file', '/etc/docker/daemon.json') | from_json }}"

    - name: set_fact original_insecure_registries
      set_fact:
        original_insecure_registries: "{{ original_content.get('insecure-registries') }}"
      when: not original_content.get('insecure_registries', False)

    - name: set_fact merged_insecure_registries
      set_fact:
        merged_insecure_registries: "{{ insecure_registries }} + {{ original_insecure_registries | difference(insecure_registries) }}"
      when: not original_content.get('insecure_registries', False)

    - name: new_content
      set_fact:
        new_content: "{{ '{ \"insecure-registries\": insecure_registries }' if not original_content.get('insecure-registries', False) else '{ \"insecure-registries\": insecure_registries + merged_insecure_registries }' }}"

    - name: add registry name to the list of insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: "{{ new_content }}"
        notify: restart docker

  handlers:
    - name: restart docker
      service:
         name: docker
         state: restarted
         enabled: yes
